name: Deploy to neocities

on:
  push:
    branches:
      - main  # or 'master' if that's your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.f5bb31bd07c558fdba6b2cdcc45d289d }}
          cleanup: true  # Remove files that aren't in your build
          dist_dir: public  # Your site is in the public folder